/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CarController;
import Model.CarModel;
import Model.OwnerModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan Tshat Joe
 */
public class CarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CarView
     */
    public CarView() {
        initComponents();
    }
        CarController ccont = new CarController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        platetxt = new javax.swing.JTextField();
        modeltxt = new javax.swing.JTextField();
        typetxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        ownernametxt = new javax.swing.JTextField();
        ownercontacttxt = new javax.swing.JTextField();
        taxtxt = new javax.swing.JTextField();
        nettxt = new javax.swing.JTextField();
        ownercombo = new javax.swing.JComboBox<>();
        deletebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("PlateNo");

        jLabel2.setText("Owner");

        jLabel3.setText("Model");

        jLabel4.setText("Type");

        jLabel5.setText("Price");

        jLabel6.setText("Tax");

        jLabel7.setText("Net");

        jLabel8.setText("Owner's names");

        jLabel9.setText("Owner's Contact");

        platetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platetxtActionPerformed(evt);
            }
        });

        modeltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeltxtActionPerformed(evt);
            }
        });

        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });

        pricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtActionPerformed(evt);
            }
        });

        ownernametxt.setEditable(false);
        ownernametxt.setBackground(new java.awt.Color(204, 204, 204));
        ownernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownernametxtActionPerformed(evt);
            }
        });

        ownercontacttxt.setEditable(false);
        ownercontacttxt.setBackground(new java.awt.Color(204, 204, 204));
        ownercontacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownercontacttxtActionPerformed(evt);
            }
        });

        taxtxt.setEditable(false);
        taxtxt.setBackground(new java.awt.Color(204, 204, 204));
        taxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxtxtActionPerformed(evt);
            }
        });

        nettxt.setEditable(false);
        nettxt.setBackground(new java.awt.Color(204, 204, 204));
        nettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nettxtActionPerformed(evt);
            }
        });

        ownercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "1", "2", "3", "4", "5" }));
        ownercombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownercomboActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        savebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                savebtnKeyReleased(evt);
            }
        });

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PlateNo", "Model", "Type", "Price", "OwnerId"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(platetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ownercombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(typetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nettxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(taxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ownernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ownercontacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addComponent(deletebtn)
                                .addGap(40, 40, 40)
                                .addComponent(savebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearbtn)
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 569, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(platetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nettxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ownercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(ownernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ownercontacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletebtn)
                            .addComponent(savebtn)
                            .addComponent(clearbtn)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void platetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platetxtActionPerformed

    private void modeltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeltxtActionPerformed

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typetxtActionPerformed

    private void pricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtActionPerformed

    private void ownernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownernametxtActionPerformed

    private void ownercontacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownercontacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownercontacttxtActionPerformed

    private void taxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxtxtActionPerformed

    private void nettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nettxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nettxtActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        CarModel c = new CarModel();
        
        c.setPlateNo(platetxt.getText());
        c.setModel(modeltxt.getText());
        c.setType(typetxt.getText());
        c.setPrice(Double.parseDouble(pricetxt.getText()));
        
        
        ccont.CControl(c);
        
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        model.insertRow(model.getRowCount(), new Object[]{platetxt.getText(), modeltxt.getText(), typetxt.getText(),
        pricetxt.getText(),ownercombo.getSelectedItem()
       
            });
       
        calculate();
        combobx();
    }//GEN-LAST:event_savebtnActionPerformed

    private void ownercomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownercomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownercomboActionPerformed

    private void savebtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_savebtnKeyReleased
        calculate();
    }//GEN-LAST:event_savebtnKeyReleased

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        CarModel d =new CarModel();
        
        d.setPlateNo(platetxt.getText());
        
        ccont.delete(d);
    }//GEN-LAST:event_deletebtnActionPerformed
    
    public void combobx(){
        OwnerModel cbx = new OwnerModel();
        
        Integer IdNumber = Integer.parseInt((String) ownercombo.getSelectedItem());
        
        String Owner_name= cbx.getFirstName()  +  cbx.getLastName();
        String Owner_contact=cbx.getPhoneNumber();
        
        ownernametxt.setText(Owner_name+"");
        ownercontacttxt.setText(Owner_contact+"");
    }
    
    public void calculate(){
        Double price = Double.parseDouble(pricetxt.getText());
        
        Double tax = (price*60)/100;
        Double net = price + tax;
        
        taxtxt.setText(tax +"");
        nettxt.setText(net +"");
    }
    
    public void clear(){
     platetxt.setText("");
     modeltxt.setText("");
     typetxt.setText("");
     pricetxt.setText("");
     taxtxt.setText("");
     nettxt.setText("");
     ownercombo.setSelectedItem("");
     ownernametxt.setText("");
     ownercontacttxt.setText("");
        
     DefaultTableModel model=(DefaultTableModel) jTable1.getModel();        
     model.setRowCount(0);
     
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField modeltxt;
    private javax.swing.JTextField nettxt;
    private javax.swing.JComboBox<String> ownercombo;
    private javax.swing.JTextField ownercontacttxt;
    private javax.swing.JTextField ownernametxt;
    private javax.swing.JTextField platetxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField taxtxt;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
